import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nikola Marić</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex flex-col pt-16 px-2 lg:px-36 2xl:px-80 ">
        {/* Portrait and headers */}
        <div className="flex items-center justify-between lg:justify-start my-4 ">
          <Image
            alt=""
            src="/portrait.svg"
            width={50}
            height={50}
            className="w-24 h-24 lg:w-32 lg:h-32 lg:mr-4 ease-in-out duration-150 hover:scale-105 hover:rotate-2"
          />
          <div className="flex flex-col items-start">
            <h1 className="text-4xl font-medium">Nikola Marić</h1>
            <h2 className="text-2xl text-customgold ">Full-Stack Web Dev👨‍💻</h2>
          </div>
        </div>

        {/* Description */}
        <p className="text-lg lg:text-2xl my-4 px-2">
          I have always been deeply passionate for problem-solving and exploring
          new technology. I am driven to constantly expand my skillset and
          knowledge, as I believe that this is crucial for staying ahead in this
          fast-paced and ever-evolving industry.
        </p>

        {/* Skills section */}
        <div className="my-4">
          <h2 className="text-2xl underline">Skills:</h2>
          <div className="flex flex-wrap text-xl lg:text-3xl">
            <div className="flex m-1 items-center">
              <Image
                src="/iconHTML.svg"
                width={20}
                height={20}
                className="lg:w-8 lg:h-8"
              />
              <p>HTML</p>
            </div>
            <div className="flex m-1 items-center">
              <Image
                src="/iconCSS.svg"
                width={20}
                height={20}
                className="lg:w-8 lg:h-8"
              />
              <p>CSS</p>
            </div>
            <div className="flex m-1 items-center">
              <Image
                src="/iconTAILWIND.svg"
                width={20}
                height={20}
                className="lg:w-8 lg:h-8"
              />
              <p>TailwindCSS</p>
            </div>
            <div className="flex m-1 items-center">
              <Image
                src="/iconJS.svg"
                width={20}
                height={20}
                className="lg:w-8 lg:h-8"
              />
              <p>JavaScript</p>
            </div>
            <div className="flex m-1 items-center">
              <Image
                src="/iconREACT.svg"
                width={20}
                height={20}
                className="lg:w-8 lg:h-8"
              />
              <p>React</p>
            </div>
            <div className="flex m-1 items-center">
              <Image
                src="/iconNEXT.svg"
                width={20}
                height={20}
                className="lg:w-8 lg:h-8"
              />
              <p>Next.js</p>
            </div>
            <div className="flex m-1 items-center">
              <Image
                src="/iconNODE.svg"
                width={20}
                height={20}
                className="lg:w-8 lg:h-8"
              />
              <p>Node.js</p>
            </div>
            <div className="flex m-1 items-center">
              <Image
                src="/iconEXPRESS.svg"
                width={20}
                height={20}
                className="lg:w-8 lg:h-8"
              />
              <p>Express.js</p>
            </div>
            <div className="flex m-1 items-center">
              <Image
                src="/iconFIREBASE.svg"
                width={20}
                height={20}
                className="lg:w-8 lg:h-8"
              />
              <p>Firebase</p>
            </div>
            <div className="flex m-1 items-center">
              <Image
                src="/iconGIT.svg"
                width={20}
                height={20}
                className="lg:w-8 lg:h-8"
              />
              <p>Git</p>
            </div>
            <div className="flex m-1 items-center">
              <Image
                src="/iconFIGMA.svg"
                width={20}
                height={20}
                className="lg:w-8 lg:h-8"
              />
              <p>Figma</p>
            </div>
          </div>
        </div>
        <Link href="/projects" className="text-xl text-customgold linkButton">
          Check out some of my projects 👉
        </Link>
      </main>
    </>
  );
}
